// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfgswiuabhhnvgscfnok.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmZ3N3aXVhYmhobnZnc2Nmbm9rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyODY5ODEsImV4cCI6MjA5Nzg2Mjk4MX0.9Y1lSW8gQ-r1AgFbvz_jN3gYsAANk9i5u6ub7TGWKws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});